channels:
  - conda-forge
  - bioconda
dependencies:
  - python
  - numpy
  - pandas
  - biopython
  - seqtk
  - fastqc
  - blast
  - muscle
  - taxonkit
  - iqtree
  - entrez-direct
  - seqkit
  - matplotlib
  - trimal
  - pip
  - figtree
  - aliview
