channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  - python
  - numpy
  - pandas
  - biopython
  - seqtk
  - fastqc
  - blast
  - muscle
  - taxonkit
  - iqtree
  - entrez-direct
  - seqkit
  - matplotlib
  - trimal
  - mafft
  - aliview
  - catfasta2phyml
  - pip
