channels:
  - conda-forge
  - bioconda
dependencies:
  - python
  - numpy
  - pandas
  - biopython
  - seqtk
  - fastqc
  - blast
  - taxonkit
  - aliview
  - iqtree
  - figtree
  - entrez-direct
  - seqkit
  - matplotlib
  - pip
